baseURL: 'https://blog-qa.groupdocs.com/'
languageCode: 'en-us'
title: 'GroupDocs'
theme: "PaperMod"
paginate: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
  env: staging # to enable google analytics, opengraph, twitter-cards and schema.
  title: Groupdocs Blog
  description: "Learn how to smartly manipulate File Formats of Word, Excel, PDF, PowerPoint, Outlook, Visio, Photoshop, 3D, GIS, and more than 100 other file formats using native APIs for .NET & Java."
  keywords: ["excel c#", "pdf c#", "word api c#", "c# electronic signature", "java digital signature pdf", "document viewer api", "digital signature api", "sign digital signature", "pdf signature api", "signature api", "document converter api", "c# data to excel", "read excel file c#", "pdf editor api"]
  mainSections: # Add name of each folder under content folder that contains blog posts.
  - Groupdocs.Blog # https://gohugo.io/functions/where/#mainsections
  ShowShareButtons: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  disableSpecial1stPost: true

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40

deployment:
  targets:
    name: "staging"
    URL: "s3://blog-qa.groupdocs.com/?region=us-west-2"
